version: "3.7"

services:
  app:
    build: .
    ports:
      - "8090:8090"
    networks:
      - s-network

  postgres:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_USER: navin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: ankit
    ports:
      - 5432:5432
    networks:
      - s-network
    volumes:
      - postgres-s-data:/var/lib/postgresql/data

networks:
  s-network:
    driver: bridge

volumes:
  postgres-s-data: